const { spawnSync, spawn } = require('child_process')
const { existsSync, writeFileSync } = require('fs')
const path = require('path')

const SESSION_ID = 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTUhLUXdTTmpsTzdKcFVlMDQyS0F3VnFBS1gxcXVEUDVHZWo5NE54cjRsMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTVhHc0ZYMXduMHhnbGJROE5iMlFjc2JKSFppV2NsSlY2cEI4L1VaSDgwST0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJFRm91em5GUVY5NTR3ZlhSYUprTzdqRU5uT05XMmRFbnRpdUNDQzJkS1djPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI1VzN4QkJISVhjZE9qUnR6NnhzU1lvbkhpVWUyZERidVZBUXJJUFVhaG5zPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IitBQTVqcllOdENiN3pjclpnMHlTdGcxMjRiY1JsZzRLR0QrRjZaL1dWRmc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ikl5dENkRW0rM3Q5T3BNRTh2dzNHYzJYRGpwL0ZOTE4xeUVvZ0Z2S0lRMnM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiR1B2TTVkVmdWM0NWS3FqNHdSbkZTTXlTNkRGU0V5SjhkVTVPQ203K2RGST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicmhQTDBFME5FNENjcjY4SndwSmJpQ3J5VkhQUUlsSnNMQ0piRlRVVmVFTT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Iit3Q1FvamMxNUVvcTZSdzA4TTN6YnFqSDVGcW5vL2pOTnMxWVpJNER2S2tUcUFwQ0I5bVJPTzZjeW1aQVpsZmFSd2xaRVhQdDhZZXRXcmZZNG9wZ0FRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTMwLCJhZHZTZWNyZXRLZXkiOiJZNnZpck9iMmVzTmNsR2JrTzk0TTExQjlJeDBxbXQ0WHFHbzdNSDZsY21BPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJuLXpqaVhEN1FqR01xWTBRYko0a3l3IiwicGhvbmVJZCI6ImY4NTM3MzMyLTczMDQtNDUzYS1hYWExLTIxZWIwMGFiZDkxYiIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ1dlMvc1kxZStGdGMxUGpjQWFVN2hUMFZyYUk9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYitGRjRhWFhaa0lBTFI2SWU4c0dWdXBKbGowPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IjVMNjE2Wlg2IiwibWUiOnsiaWQiOiI5MjMwNTIyMDY0NjU6NkBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiLwnZeg8J2YgvCdmIfwnZeu8J2XuvCdl7rwnZe28J2XufCWo5jwnZel8J2XrvCdl7vwnZe2IPCdl7TwnZeu8J2XuvCdl7bwnZe78J2XtCDKuOG1lyJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDT2JsNzZzQ0VLNlF0THNHR0FRZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiU1FHSmU5VmNBc1IxVnFxWGhlWGppb2pVSXR6S09sdStCV0pNRGk0bGtCOD0iLCJhY2NvdW50U2lnbmF0dXJlIjoiNjVnRmxkMm1JbWNHMVFoTDI0UzRHUlRCa3pHMUJHeE1lTWo1RnVYTUR0V01CaGJCT3ZDT0txVVczNzd3NzJDTFdWWEtTdWVPNVF6elBRSHRUc2gyQlE9PSIsImRldmljZVNpZ25hdHVyZSI6IjNPYjkrNGdKY1FTK0daOEFtN3dQbnR3ZVY0Z1V5a25ScWsvWlZIZ2xkY0M5VWNHVTJTNmt1SzBVZ2YxRGNnRWgyUDRSWVVMN085SzZSWTdaV25tQkFnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiOTIzMDUyMjA2NDY1OjZAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCVWtCaVh2VlhBTEVkVmFxbDRYbDQ0cUkxQ0xjeWpwYnZnVmlUQTR1SlpBZiJ9fV0sInBsYXRmb3JtIjoic21iYSIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczNTE5ODc3OCwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFFdlYifQ==' // Edit this line only, don't remove ' <- this symbol

function startNode() {
  const child = spawn('node', ['index.js'], { cwd: 'levanter', stdio: 'inherit' })

  child.on('exit', (code) => {
    if (code === 102) {
      console.log('restarting...')
      startNode()
    }
  })
}

function startPm2() {
  const pm2 = spawn('pm2', ['start', 'index.js', '--name', 'levanter', '--attach'], {
    cwd: 'levanter',
    stdio: ['pipe', 'pipe', 'pipe'],
  })

  let restartCount = 0
  const maxRestarts = 5 // Adjust this value as needed

  pm2.on('exit', (code) => {
    if (code !== 0) {
      // console.log('pm2 failed to start, falling back to node...')
      startNode()
    }
  })

  pm2.on('error', (error) => {
    // console.error(`pm2 error: ${error.message}`)
    startNode()
  })

  // Check for infinite restarts
  if (pm2.stderr) {
    pm2.stderr.on('data', (data) => {
      const output = data.toString()
      if (output.includes('restart')) {
        restartCount++
        if (restartCount > maxRestarts) {
          // console.log('pm2 is restarting indefinitely, stopping pm2 and starting node...')
          spawnSync('pm2', ['delete', 'levanter'], { cwd: 'levanter', stdio: 'inherit' })
          startNode()
        }
      }
    })
  }

  if (pm2.stdout) {
    pm2.stdout.on('data', (data) => {
      const output = data.toString()
      console.log(output)
      if (output.includes('online')) {
        // console.log('Application is online.')
        restartCount = 0
      }
    })
  }
}

function installDependencies() {
  console.log('Installing dependencies...')
  const installResult = spawnSync(
    'yarn',
    ['install', '--force', '--non-interactive', '--network-concurrency', '3'],
    {
      cwd: 'levanter',
      stdio: 'inherit',
    }
  )

  if (installResult.error) {
    throw new Error(`Failed to install dependencies: ${installResult.error.message}`)
  }
}

function checkDependencies() {
  if (!existsSync(path.resolve('levanter/package.json'))) {
    console.error('package.json not found!')
    process.exit(1)
  }

  const result = spawnSync('yarn', ['check', '--verify-tree'], { cwd: 'levanter', stdio: 'inherit' })

  // Check the exit code to determine if there was an error
  if (result.status !== 0) {
    // console.error('Some dependencies are missing or incorrectly installed.')
    installDependencies()
  } else {
    // console.log('All dependencies are installed properly.')
  }
}

function installDependencies() {
  // console.log('Installing missing dependencies...')
  const result = spawnSync('yarn', ['install'], { cwd: 'levanter', stdio: 'inherit' });

  if (result.status === 0) {
    // console.log('Dependencies installed successfully.')
  } else {
    console.error('Failed to install dependencies.')
    process.exit(1);
  }
}

function cloneRepository() {
  console.log('Cloning the repository...')
  const cloneResult = spawnSync(
    'git',
    ['clone', 'https://github.com/Mujjilounda/WASI-MD-V.git', 'levanter'],
    {
      stdio: 'inherit',
    }
  )

  if (cloneResult.error) {
    throw new Error(`Failed to clone the repository: ${cloneResult.error.message}`)
  }

  const configPath = 'levanter/config.env'
  try {
    console.log('Writing to config.env...')
    writeFileSync(configPath, `VPS=true\nSESSION_ID=${SESSION_ID}`)
  } catch (err) {
    throw new Error(`Failed to write to config.env: ${err.message}`)
  }

  installDependencies()
}

if (!existsSync('levanter')) {
  cloneRepository()
  checkDependencies()
} else {
  checkDependencies()
}

startPm2()
